### PR TITLE
add hi3650

### PR DESCRIPTION
**Pull request by sanshu-rom**
add kirin95x

### CODE REVIEW

**Comment by phhusson** [comment]
Please rebase it, there are conflicts.

**Comment by sanshu-rom** [comment]
ok

**Comment by phhusson** [comment]
please rebase, not merge

**Comment by phhusson** [comment]
perfect, thanks

**Comment by phhusson** [comment]
wait no
Why are there still 4 commits

**Comment by phhusson** [comment]
ok I'll cherry-pick it

**Comment by sanshu-rom** [comment]
@phhusson thanks

**Comment by phhusson** [comment]
Merged in https://github.com/phhusson/platform_frameworks_opt_telephony/commit/c725d06d991e745e53e6fce69796f46b710151c9

**Pull request closed without merging**
